export const data = [
  {
    id: 1,
    name: "smccullough0",
    email: "jmiguel0@google.es",
    birthDate: "2011-07-31",
  },
  {
    id: 2,
    name: "kguthrie1",
    email: "aburel1@weebly.com",
    birthDate: "2019-08-14",
  },
  {
    id: 3,
    name: "cdibb2",
    email: "phumfrey2@tripadvisor.com",
    birthDate: "2015-02-11",
  },
  {
    id: 4,
    name: "eellicott3",
    email: "nlissandrini3@blog.com",
    birthDate: "2012-02-29",
  },
  {
    id: 5,
    name: "dmcvittie4",
    email: "mseeger4@sun.com",
    birthDate: "2011-08-15",
  },
  {
    id: 6,
    name: "imullaney5",
    email: "hlongstreet5@squarespace.com",
    birthDate: "2022-02-21",
  },
  {
    id: 7,
    name: "vvasilik6",
    email: "cskones6@nhs.uk",
    birthDate: "2017-04-05",
  },
  {
    id: 8,
    name: "dcoulson7",
    email: "grame7@ebay.com",
    birthDate: "2011-07-18",
  },
  {
    id: 9,
    name: "vosler8",
    email: "dvuitton8@cloudflare.com",
    birthDate: "2019-06-08",
  },
  {
    id: 10,
    name: "aantonchik9",
    email: "dgrise9@howstuffworks.com",
    birthDate: "2021-06-14",
  },
  {
    id: 11,
    name: "anibloea",
    email: "finglesona@usnews.com",
    birthDate: "2017-06-23",
  },
  {
    id: 12,
    name: "nudyb",
    email: "mbarkusb@hibu.com",
    birthDate: "2013-02-18",
  },
  {
    id: 13,
    name: "kmarchantc",
    email: "sjumpc@163.com",
    birthDate: "2021-01-16",
  },
  {
    id: 14,
    name: "kgorbelld",
    email: "ndaniellsd@paginegialle.it",
    birthDate: "2012-06-19",
  },
  {
    id: 15,
    name: "nmalloye",
    email: "lchallonere@icq.com",
    birthDate: "2020-10-15",
  },
  {
    id: 16,
    name: "lburdassf",
    email: "agilhouleyf@digg.com",
    birthDate: "2019-08-05",
  },
  {
    id: 17,
    name: "dcanng",
    email: "tlanfranconig@list-manage.com",
    birthDate: "2014-03-26",
  },
  {
    id: 18,
    name: "chuntlyh",
    email: "pmewish@hhs.gov",
    birthDate: "2018-11-26",
  },
  {
    id: 19,
    name: "llewingtoni",
    email: "bleckiei@skyrock.com",
    birthDate: "2015-07-01",
  },
  {
    id: 20,
    name: "kmcallanj",
    email: "vgawthorpej@instagram.com",
    birthDate: "2020-02-18",
  },
];
